### ISSUE TITLE
Violent deprecation warnings vs sqlalchemy 1.4.46

### ISSUE THREAD

**Issue by bollwyvl** [RDFLib/rdflib-sqlalchemy#100] opened 2023-01-20 19:43 UTC
Use of `rdflib_sqlalchemy.store.union_select` with `sqlalchemy 1.4.46` shows:

```
The legacy calling style of select() is deprecated and will be removed in SQLAlchemy 2.0.  Please use the new calling style described at select(). (Background on SQLAlchemy 2.0 at: https://sqlalche.me/e/b8d9)
```

It's possible to hide these errors with `SQLALCHEMY_SILENCE_UBER_WARNING=1`, but it can be difficult to reason about this error, and how a downstream would be able to effectively do it.

**Comment by mwatts15** [comment] 2023-01-27 22:29
Hi, thanks for reporting this. I'll try to address the issue, but I'm short
on time for rdflib-sqlalchemy and think the project could use a new
maintainer. If you're interested, let me know.

**Comment by richardscholtens** [comment] 2023-12-01 10:10
I am updating the library to use SQLAlchemy version 2.0.23. Doing so results in the failing of multiple tests. I believe this is also has to do with the deprecation of the `select()` and similar constructs. I already fixed the first test and will continue to fix the rest as well.

**Comment by richardscholtens** [comment] 2023-12-04 14:06
@mwatts15 , so I fixed all tests but one. I'm still unable to get the `test_contexts_result` under `test_sqlalchemy` to work. The test is as follows:

```python
class SQLATestCase(unittest.TestCase):
    identifier = URIRef("rdflib_test")
    dburi = Literal("sqlite://")

    def setUp(self):
        self.store = plugin.get(
            "SQLAlchemy", Store)(identifier=self.identifier, configuration=self.dburi)
        self.graph = ConjunctiveGraph(self.store, identifier=self.identifier)
        self.graph.open(self.dburi, create=True)

    def test_contexts_result(self):
        ctx_id = URIRef('http://example.org/context')
        g = self.graph.get_context(ctx_id)
        g.add((michel, likes, pizza))
        actual = list(self.store.contexts())
        self.assertEqual(actual[0], ctx_id)
```

So it seems that information about michel liking pizza is transferred in the graph. However, when retrieving the `store.contexts()` it fails to retrieve the data. Any ideas what might be the cause of this?

I added my commit in the links below.


[Bugfix branch issue 100](https://github.com/richardscholtens/rdflib-sqlalchemy/tree/bugfix/issue-100-update-sqlalchemy-to-version-2.0.23)
[Bugfix commit](https://github.com/RDFLib/rdflib-sqlalchemy/compare/develop...richardscholtens:rdflib-sqlalchemy:bugfix/issue-100-update-sqlalchemy-to-version-2.0.23)

**Comment by richardscholtens** [comment] 2023-12-05 09:56
So it does seems to work when the test gets a adjusted a little bit.

```python
def test_contexts_result(self):
    ctx_id = URIRef('http://example.org/context')
    g = self.graph.get_context(ctx_id)
    g.add((michel, likes, pizza))
    actual = list(self.store.contexts(triple=(michel, likes, pizza)))
    self.assertEqual(actual[0], ctx_id)
```

Here I fill in the parameter `triple` so it know exactly which triple to look for and only retrieves the contexts it is in. This means it does store the triple somewhere in the contexts. Also see this [context function reference](https://rdflib.readthedocs.io/en/stable/apidocs/rdflib.plugins.stores.html#rdflib.plugins.stores.auditable.AuditableStore.contexts)

I've also started a pull request.

**Comment by mwatts15** [comment] 2023-12-05 11:57
Good catch, Richard. It should definitely work without the triple argument
passed in. My first guess at why it might not is a change in how SQLAlchemy
generates the query or stores the triples. More verbose logging should help
determine what the cause is.

**Comment by richardscholtens** [comment] 2023-12-05 12:41
I believe it has to do with the following code:

```python
# sql.py line 68
        elif select_type == CONTEXT_SELECT:
            select_clause = expression.select(*[table.c.context]).where(whereClause)
        
```
If I change it to the code below the test `test_contexts_results` works, but then `test_contexts_with_triple` fails.

```python
# sql.py line 68
        elif select_type == CONTEXT_SELECT:
            select_clause = expression.select(table.c.context)
            if whereClause:
                select_clause = expression.select(table.c.context).where(whereClause)
```

New error:

```shell
    def __bool__(self):
>       raise TypeError("Boolean value of this clause is not defined")
E       TypeError: Boolean value of this clause is not defined

```

**Comment by richardscholtens** [comment] 2023-12-05 13:01
Ah never mind. Already fixed it with;

```python
if whereClause is not None:
```

I believe the pull request is ready for reviewing, @mwatts15

**Comment by mwatts15** [comment] 2023-12-07 00:01
Sounds good. I will try to merge in the next few days.

**Comment by richardscholtens** [comment] 2023-12-07 08:56
Thanks! Let me know if there are any issues.

**Comment by richardscholtens** [comment] 2023-12-11 10:42
I noticed I still had an old commit message in the PR.  Updated this PR comment.

**Comment by richardscholtens** [comment] 2024-02-06 10:12
@mwatts15, I pushed a new fix for one of the bugs. All Postgres test seem to work now. Did not test on the other databases. Could you rerun the pipeline for me?

[PR-104](https://github.com/RDFLib/rdflib-sqlalchemy/pull/104)

**Comment by richardscholtens** [comment] 2024-02-13 07:34
@mwatts15 , I believe this issue can be closed now.

**Closed as completed** 2024-02-21 22:32 UTC
